### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Atrate** [bagaswastu/librebook#1]
Hey there!

How would one contribute translations to this project? I've looked in `/lib` for the `l10n` folder as many Dart apps use it (e.g. https://github.com/manuelvargastapia/libgen_mobile_app/pull/6/files), but I could not find it.

Regards,
Atrate

**Comment by bgwastu** [comment]
Hi Atare, thank you for your enthusiasm for this project

Right now this application don't have localizations yet, I will consider adding this feature in the future but no ETA

**Comment by pavelzw** [comment]
Hi,
I created a basic structure that allows localizations (#2). 
If that's fine with @bagaswastu, one could use that for localizations.
