### ISSUE TITLE
Cover for fantasy books.

### ISSUE THREAD

**Issue by sgrxrx** [bagaswastu/librebook#11]
the cover for fantasy books are not displaying

**Comment by sgrxrx** [comment]
https://i.imgur.com/s1UdNcR.jpg

**Comment by bgwastu** [comment]
Thank you for your report, I will try to investigate this problem further

**Comment by bgwastu** [comment]
Fixed, the updated app can be downloaded in [here](https://codemagic.io/apps/6003d2461b08f3ec61b49785/6003d2461b08f3ec61b49784/latest_build)

**Comment by sgrxrx** [comment]
Thanks man:)
